version: "3.8"
services:
  app:
    image: modtoberfest/site
    build:
    # !!! Make sure your file is there
    # Or simply provide the environment variables
    # directly in this file
    network_mode: "host"
    env_file: .env
    ports:
      - 3000:3000
